sudo: required

go_import_path: github.com/KyberNetwork/reserve-data

language: go

services:
  - docker

install:
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install
  - go get github.com/mattn/goveralls

script:
  - gometalinter --config=gometalinter.json ./...
  - go test -v ./...

after_success:
  - docker --version
  - docker build -f Dockerfile.next -t kybernetwork/reserve-data:$TRAVIS_COMMIT .
  - docker run -v $PWD/apidocs/build/:/slate/build/ -v $PWD/apidocs/source/:/slate/source/ kybernetwork/slate:latest

deploy:
  provider: script
  script: bash .travis/docker_push
  on:
    all_branches: true

go:
  - "1.10.x"
