// Code generated by "stringer -type=AddressSetName -linecomment"; DO NOT EDIT.

package settings

import "strconv"

const _AddressSetName_name = "third_party_reservesold_networksold_burners"

var _AddressSetName_index = [...]uint8{0, 20, 32, 43}

func (i AddressSetName) String() string {
	if i < 0 || i >= AddressSetName(len(_AddressSetName_index)-1) {
		return "AddressSetName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AddressSetName_name[_AddressSetName_index[i]:_AddressSetName_index[i+1]]
}
